/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as QuotaRouteImport } from './routes/quota'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TokenSaverRouteImport } from './routes/token-saver'
import { Route as ProvidersIndexRouteImport } from './routes/providers/index'
import { Route as ProvidersProviderIdRouteImport } from './routes/providers/$providerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotaRoute = QuotaRouteImport.update({
  id: '/quota',
  path: '/quota',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenSaverRoute = TokenSaverRouteImport.update({
  id: '/token-saver',
  path: '/token-saver',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvidersRoute,
} as any)
const ProvidersProviderIdRoute = ProvidersProviderIdRouteImport.update({
  id: '/$providerId',
  path: '/$providerId',
  getParentRoute: () => ProvidersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/keys': typeof KeysRoute
  '/logs': typeof LogsRoute
  '/playground': typeof PlaygroundRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/quota': typeof QuotaRoute
  '/settings': typeof SettingsRoute
  '/token-saver': typeof TokenSaverRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/providers/': typeof ProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/keys': typeof KeysRoute
  '/logs': typeof LogsRoute
  '/playground': typeof PlaygroundRoute
  '/quota': typeof QuotaRoute
  '/settings': typeof SettingsRoute
  '/token-saver': typeof TokenSaverRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/providers': typeof ProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/keys': typeof KeysRoute
  '/logs': typeof LogsRoute
  '/playground': typeof PlaygroundRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/quota': typeof QuotaRoute
  '/settings': typeof SettingsRoute
  '/token-saver': typeof TokenSaverRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/providers/': typeof ProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/keys'
    | '/logs'
    | '/playground'
    | '/providers'
    | '/quota'
    | '/settings'
    | '/token-saver'
    | '/providers/$providerId'
    | '/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/keys'
    | '/logs'
    | '/playground'
    | '/quota'
    | '/settings'
    | '/token-saver'
    | '/providers/$providerId'
    | '/providers'
  id:
    | '__root__'
    | '/'
    | '/keys'
    | '/logs'
    | '/playground'
    | '/providers'
    | '/quota'
    | '/settings'
    | '/token-saver'
    | '/providers/$providerId'
    | '/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KeysRoute: typeof KeysRoute
  LogsRoute: typeof LogsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProvidersRoute: typeof ProvidersRouteWithChildren
  QuotaRoute: typeof QuotaRoute
  SettingsRoute: typeof SettingsRoute
  TokenSaverRoute: typeof TokenSaverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quota': {
      id: '/quota'
      path: '/quota'
      fullPath: '/quota'
      preLoaderRoute: typeof QuotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token-saver': {
      id: '/token-saver'
      path: '/token-saver'
      fullPath: '/token-saver'
      preLoaderRoute: typeof TokenSaverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/providers/$providerId': {
      id: '/providers/$providerId'
      path: '/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof ProvidersProviderIdRouteImport
      parentRoute: typeof ProvidersRoute
    }
  }
}

interface ProvidersRouteChildren {
  ProvidersProviderIdRoute: typeof ProvidersProviderIdRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
}

const ProvidersRouteChildren: ProvidersRouteChildren = {
  ProvidersProviderIdRoute: ProvidersProviderIdRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
}

const ProvidersRouteWithChildren = ProvidersRoute._addFileChildren(
  ProvidersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KeysRoute: KeysRoute,
  LogsRoute: LogsRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProvidersRoute: ProvidersRouteWithChildren,
  QuotaRoute: QuotaRoute,
  SettingsRoute: SettingsRoute,
  TokenSaverRoute: TokenSaverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
