// This file has been generated by Specta. Do not edit this file manually.
/**
 *  Management representation. `key_prefix` is the non-secret display prefix;
 *  the full secret is never stored, so it never appears here.
 */
export type APIKeyResponse = {
	id: string,
	key_prefix: string,
	name: string,
	enabled: boolean,
	rate_limit: number,
	quota_limit: number,
	usage_tokens: number,
	credit_limit: number | null,
	usage_cost: number | null,
	allowed_models: string[] | null,
	created_at: number,
};

/**
 *  `GET /v1/admin/status` — whether the install still needs its first admin
 *  and whether the caller holds a valid session cookie.
 */
export type AdminStatus = {
	setup_required: boolean,
	authenticated: boolean,
};

/**
 *  One time bucket of the analytics window. Missing buckets are zero-filled.
 * 
 *  Deliberate deviation from Node: this report serializes snake_case, matching
 *  the rest of the Rust `/v1/logs` surface, instead of Node's camelCase.
 */
export type AnalyticsBucket = {
	bucket_start: number,
	total_requests: number,
	success_requests: number,
	error_requests: number,
	avg_latency_ms: number | null,
	total_tokens: number,
	prompt_tokens: number,
	completion_tokens: number,
	cached_tokens: number,
};

export type AnalyticsProviderSlice = {
	provider_id: string,
	total_requests: number,
};

/**
 *  The `GET /v1/logs/analytics` report. Field names and semantics follow the
 *  Node `LogsLogic.getAnalytics` result, but snake_case rather than camelCase.
 */
export type AnalyticsReport = {
	object: string,
	window: string,
	bucket_size_ms: number,
	generated_at: number,
	requests_per_second: number | null,
	total_requests: number,
	error_rate: number | null,
	p95_latency_ms: number,
	buckets: AnalyticsBucket[],
	top_models: AnalyticsTopModel[],
	top_agents: AnalyticsTopAgent[],
	providers: AnalyticsProviderSlice[],
};

export type AnalyticsTopAgent = {
	agent: string,
	raw_user_agent: string,
	total_requests: number,
	total_tokens: number,
};

export type AnalyticsTopModel = {
	model: string | null,
	total_requests: number,
	total_tokens: number,
	est_cost: number | null,
};

export type ApiInfo = {
	name: string,
	status: string,
	version: string,
	documentation: string,
};

/**
 *  A catalog entry: the OpenAI model fields plus the operator's favorite flag
 *  and the custom-model marker Node adds in `MergeCustomModels`.
 */
export type CatalogModel = CatalogModel_Serialize | CatalogModel_Deserialize;

/**
 *  A catalog entry: the OpenAI model fields plus the operator's favorite flag
 *  and the custom-model marker Node adds in `MergeCustomModels`.
 */
export type CatalogModel_Deserialize = {
	id: string,
	object: string,
	owned_by: string,
	favorite: boolean,
	custom?: boolean | null,
};

/**
 *  A catalog entry: the OpenAI model fields plus the operator's favorite flag
 *  and the custom-model marker Node adds in `MergeCustomModels`.
 */
export type CatalogModel_Serialize = {
	id: string,
	object: string,
	owned_by: string,
	favorite: boolean,
	custom?: boolean | null,
};

/**  `GET /v1/providers/catalog`. */
export type CatalogResponse = CatalogResponse_Serialize | CatalogResponse_Deserialize;

/**  `GET /v1/providers/catalog`. */
export type CatalogResponse_Deserialize = {
	total: number,
	categories: GroupedCatalog_Deserialize,
};

/**  `GET /v1/providers/catalog`. */
export type CatalogResponse_Serialize = {
	total: number,
	categories: GroupedCatalog_Serialize,
};

/**  Fields accepted by `POST /v1/keys`, mirroring `CreateAPIKeySchema`. */
export type CreateAPIKeyInput = {
	name: string,
	enabled?: boolean,
	rate_limit?: number,
	quota_limit?: number,
	credit_limit?: number | null,
	allowed_models?: string[] | null,
};

/**  Creation response: the management fields plus the one-time full secret. */
export type CreatedAPIKeyResponse = {
	key: string,
} & APIKeyResponse;

export type ErrorBody = ErrorBody_Serialize | ErrorBody_Deserialize;

export type ErrorBody_Deserialize = {
	message: string,
	type: string,
	code?: string | null,
	param?: string | null,
};

export type ErrorBody_Serialize = {
	message: string,
	type: string,
	code?: string | null,
	param?: string | null,
};

export type ErrorEnvelope = ErrorEnvelope_Serialize | ErrorEnvelope_Deserialize;

export type ErrorEnvelope_Deserialize = {
	error: ErrorBody_Deserialize,
};

export type ErrorEnvelope_Serialize = {
	error: ErrorBody_Serialize,
};

/**  The four fixed provider groups. */
export type GroupedCatalog = GroupedCatalog_Serialize | GroupedCatalog_Deserialize;

/**  The four fixed provider groups. */
export type GroupedCatalog_Deserialize = {
	oauth: ProviderEntry_Deserialize[],
	free_tier: ProviderEntry_Deserialize[],
	api_key: ProviderEntry_Deserialize[],
	custom_provider: ProviderEntry_Deserialize[],
};

/**  The four fixed provider groups. */
export type GroupedCatalog_Serialize = {
	oauth: ProviderEntry_Serialize[],
	free_tier: ProviderEntry_Serialize[],
	api_key: ProviderEntry_Serialize[],
	custom_provider: ProviderEntry_Serialize[],
};

export type HealthResponse = {
	status: string,
};

/**
 *  Standard HTTP request methods.
 * 
 *  The wire and stored values are always one of the logged methods; a stored
 *  row that carries anything else parses to `Other` through [`FromStr`], which
 *  is where the tolerant fallback lives.
 */
export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS" | "CONNECT" | "TRACE" | "OTHER";

export type KeyListResponse = {
	object: string,
	data: APIKeyResponse[],
};

export type LiveEvent = LiveEvent_Serialize | LiveEvent_Deserialize;

export type LiveEvent_Deserialize = ({ type: "connected" }) & { log?: never; stats?: never } | ({ type: "usage.updated"; stats: UsageStatsReport }) & { log?: never } | ({ type: "request.logged"; log: RequestLog_Deserialize }) & { stats?: never };

export type LiveEvent_Serialize = ({ type: "connected" }) & { log?: never; stats?: never } | ({ type: "usage.updated"; stats: UsageStatsReport }) & { log?: never } | ({ type: "request.logged"; log: RequestLog_Serialize }) & { stats?: never };

/**  A specific rate-limit window or model quota entry. */
export type LiveModelQuotaItem = LiveModelQuotaItem_Serialize | LiveModelQuotaItem_Deserialize;

/**  A specific rate-limit window or model quota entry. */
export type LiveModelQuotaItem_Deserialize = {
	name: string,
	used: number,
	limit: number,
	percentage: string,
	percentage_value: number,
	reset_in: string,
	reset_time?: string | null,
	status: "exhausted" | "warning" | "ok",
};

/**  A specific rate-limit window or model quota entry. */
export type LiveModelQuotaItem_Serialize = {
	name: string,
	used: number,
	limit: number,
	percentage: string,
	percentage_value: number,
	reset_in: string,
	reset_time?: string | null,
	status: "exhausted" | "warning" | "ok",
};

/**  Client identification metadata for a logged request. */
export type LogClient = LogClient_Serialize | LogClient_Deserialize;

/**  Client identification metadata for a logged request. */
export type LogClient_Deserialize = {
	ip_address?: string | null,
	user_agent?: string | null,
};

/**  Client identification metadata for a logged request. */
export type LogClient_Serialize = {
	ip_address?: string | null,
	user_agent?: string | null,
};

/**  Estimated cost breakdown formatted in fixed 4-decimal USD for a logged request. */
export type LogCost = LogCost_Serialize | LogCost_Deserialize;

/**  Estimated cost breakdown formatted in fixed 4-decimal USD for a logged request. */
export type LogCost_Deserialize = {
	input?: string | null,
	output?: string | null,
	cache?: string | null,
	total?: string | null,
};

/**  Estimated cost breakdown formatted in fixed 4-decimal USD for a logged request. */
export type LogCost_Serialize = {
	input?: string | null,
	output?: string | null,
	cache?: string | null,
	total?: string | null,
};

/**  Error / diagnostics information for a failed request. */
export type LogError = LogError_Serialize | LogError_Deserialize;

/**  Error / diagnostics information for a failed request. */
export type LogError_Deserialize = {
	error_code?: string | null,
	error_message?: string | null,
};

/**  Error / diagnostics information for a failed request. */
export type LogError_Serialize = {
	error_code?: string | null,
	error_message?: string | null,
};

/**  Token usage breakdown for a logged request. */
export type LogTokenUsage = LogTokenUsage_Serialize | LogTokenUsage_Deserialize;

/**  Token usage breakdown for a logged request. */
export type LogTokenUsage_Deserialize = {
	input?: number | null,
	output?: number | null,
	cache?: number | null,
	cache_read?: number | null,
	cache_creation?: number | null,
	reasoning?: number | null,
	total?: number | null,
};

/**  Token usage breakdown for a logged request. */
export type LogTokenUsage_Serialize = {
	input?: number | null,
	output?: number | null,
	cache?: number | null,
	cache_read?: number | null,
	cache_creation?: number | null,
	reasoning?: number | null,
	total?: number | null,
};

export type LogsResponse = LogsResponse_Serialize | LogsResponse_Deserialize;

export type LogsResponse_Deserialize = {
	object: ObjectKind,
	data: RequestLog_Deserialize[],
	pagination?: Pagination | null,
};

export type LogsResponse_Serialize = {
	object: ObjectKind,
	data: RequestLog_Serialize[],
	pagination?: Pagination | null,
};

export type ModelListResponse = ModelListResponse_Serialize | ModelListResponse_Deserialize;

export type ModelListResponse_Deserialize = {
	object: string,
	data: CatalogModel_Deserialize[],
};

export type ModelListResponse_Serialize = {
	object: string,
	data: CatalogModel_Serialize[],
};

export type ModelPricingCost = ModelPricingCost_Serialize | ModelPricingCost_Deserialize;

export type ModelPricingCost_Deserialize = {
	input?: number | null,
	output?: number | null,
	cache_read?: number | null,
	cache_write?: number | null,
	reasoning?: number | null,
	input_audio?: number | null,
	output_audio?: number | null,
};

export type ModelPricingCost_Serialize = {
	input?: number | null,
	output?: number | null,
	cache_read?: number | null,
	cache_write?: number | null,
	reasoning?: number | null,
	input_audio?: number | null,
	output_audio?: number | null,
};

export type ModelPricingItem = ModelPricingItem_Serialize | ModelPricingItem_Deserialize;

export type ModelPricingItem_Deserialize = {
	id: string,
	name: string,
	description: string,
	family?: string | null,
	provider: string,
	attachment: boolean,
	reasoning: boolean,
	tool_call: boolean,
	temperature?: boolean | null,
	structured_output?: boolean | null,
	open_weights: boolean,
	knowledge?: string | null,
	release_date: string,
	last_updated: string,
	cost?: ModelPricingCost_Deserialize | null,
	limit?: ModelPricingLimit_Deserialize | null,
	modalities?: ModelPricingModalities_Deserialize | null,
};

export type ModelPricingItem_Serialize = {
	id: string,
	name: string,
	description: string,
	family?: string | null,
	provider: string,
	attachment: boolean,
	reasoning: boolean,
	tool_call: boolean,
	temperature?: boolean | null,
	structured_output?: boolean | null,
	open_weights: boolean,
	knowledge?: string | null,
	release_date: string,
	last_updated: string,
	cost?: ModelPricingCost_Serialize | null,
	limit?: ModelPricingLimit_Serialize | null,
	modalities?: ModelPricingModalities_Serialize | null,
};

export type ModelPricingLimit = ModelPricingLimit_Serialize | ModelPricingLimit_Deserialize;

export type ModelPricingLimit_Deserialize = {
	context?: number | null,
	output?: number | null,
};

export type ModelPricingLimit_Serialize = {
	context?: number | null,
	output?: number | null,
};

export type ModelPricingModalities = ModelPricingModalities_Serialize | ModelPricingModalities_Deserialize;

export type ModelPricingModalities_Deserialize = {
	input?: string[] | null,
	output?: string[] | null,
};

export type ModelPricingModalities_Serialize = {
	input?: string[] | null,
	output?: string[] | null,
};

export type ObjectKind = "list" | "usage";

export type Pagination = {
	page: number,
	limit: number,
	total: number,
	total_pages: number,
};

export type PricingListResponse = PricingListResponse_Serialize | PricingListResponse_Deserialize;

export type PricingListResponse_Deserialize = {
	object: string,
	total: number,
	updated_at?: string | null,
	data: ModelPricingItem_Deserialize[],
};

export type PricingListResponse_Serialize = {
	object: string,
	total: number,
	updated_at?: string | null,
	data: ModelPricingItem_Serialize[],
};

/**
 *  A connection as the detail response reports it. There is deliberately no
 *  credential field: a stored API key never leaves the database.
 */
export type ProviderConnectionView = {
	id: string,
	provider_id: string,
	name: string,
	alias: string | null,
	category: string,
	protocol: string,
	base_url: string | null,
	enabled: boolean,
	created_at: number,
};

/**  A provider as the list, catalog, and detail routes describe it. */
export type ProviderEntry = ProviderEntry_Serialize | ProviderEntry_Deserialize;

/**  A provider as the list, catalog, and detail routes describe it. */
export type ProviderEntry_Deserialize = {
	id: string,
	name: string,
	category: string,
	protocol: ProviderProtocol,
	default_base_url: string,
	requires_api_key: boolean,
	requires_oauth: boolean,
	supports_custom_url: boolean,
	enabled: boolean,
	/**  Whether requests rotate across this provider's accounts. */
	round_robin: boolean,
	status: ProviderStatus,
	/**  Detail only; the list and catalog omit it like Node does. */
	connections?: ProviderConnectionView[] | null,
	models: ProviderModel[],
};

/**  A provider as the list, catalog, and detail routes describe it. */
export type ProviderEntry_Serialize = {
	id: string,
	name: string,
	category: string,
	protocol: ProviderProtocol,
	default_base_url: string,
	requires_api_key: boolean,
	requires_oauth: boolean,
	supports_custom_url: boolean,
	enabled: boolean,
	/**  Whether requests rotate across this provider's accounts. */
	round_robin: boolean,
	status: ProviderStatus,
	/**  Detail only; the list and catalog omit it like Node does. */
	connections?: ProviderConnectionView[] | null,
	models: ProviderModel[],
};

export type ProviderListResponse = ProviderListResponse_Serialize | ProviderListResponse_Deserialize;

export type ProviderListResponse_Deserialize = {
	object: string,
	data: ProviderEntry_Deserialize[],
};

export type ProviderListResponse_Serialize = {
	object: string,
	data: ProviderEntry_Serialize[],
};

/**
 *  A model line in the detail response. Hidden and favorited models stay in the
 *  list so the admin view can restore them; `GET /v1/models` is the route that
 *  drops them.
 */
export type ProviderModel = {
	id: string,
	object: string,
	owned_by: string,
	hidden: boolean,
	favorite: boolean,
};

/**
 *  The wire protocol a provider speaks, as the catalog and the provider-auth
 *  responses report it.
 * 
 *  Three variants, matching what the build actually serves. Node's
 *  `ProviderProtocol` union also lists `gemini`, but that value is dead: its only
 *  user was the `gemini_cli` provider deleted with `packages/providers/src/catalog.ts`.
 */
export type ProviderProtocol = "openai" | "anthropic" | "custom";

/**  An account's quota overview. */
export type ProviderQuotaAccount = ProviderQuotaAccount_Serialize | ProviderQuotaAccount_Deserialize;

/**  An account's quota overview. */
export type ProviderQuotaAccount_Deserialize = {
	id: string,
	provider: string,
	account: string,
	enabled: boolean,
	quota_type: string,
	total_quotas?: number | null,
	quotas?: LiveModelQuotaItem_Deserialize[] | null,
	usage_metrics?: ProviderUsageMetric[] | null,
};

/**  An account's quota overview. */
export type ProviderQuotaAccount_Serialize = {
	id: string,
	provider: string,
	account: string,
	enabled: boolean,
	quota_type: string,
	total_quotas?: number | null,
	quotas?: LiveModelQuotaItem_Serialize[] | null,
	usage_metrics?: ProviderUsageMetric[] | null,
};

/**  Connection state of a provider driver. */
export type ProviderStatus = {
	state: "connected" | "no_connections",
	message: string,
	connected_count: number,
};

/**
 *  One `usage_metrics` row: what a provider driver reports about a model's
 *  logged usage.
 * 
 *  No driver in this build fills it (`usage_metrics` is always `None`), but the
 *  shape is the one Node declares (`packages/types/src/quota.ts`,
 *  `ProviderUsageMetric`), so a client can read the field without a hole in its
 *  types.
 */
export type ProviderUsageMetric = {
	model: string,
	total_requests: number,
	total_tokens: number,
	prompt_tokens: number,
	completion_tokens: number,
	last_used_at: string | null,
};

/**  Top-level response for `GET /v1/quota` and `GET /v1/qouta`. */
export type QuotaResponse = QuotaResponse_Serialize | QuotaResponse_Deserialize;

/**  Top-level response for `GET /v1/quota` and `GET /v1/qouta`. */
export type QuotaResponse_Deserialize = {
	object: string,
	total_accounts: number,
	providers: ProviderQuotaAccount_Deserialize[],
};

/**  Top-level response for `GET /v1/quota` and `GET /v1/qouta`. */
export type QuotaResponse_Serialize = {
	object: string,
	total_accounts: number,
	providers: ProviderQuotaAccount_Serialize[],
};

/**
 *  A single request-log record. Categorized into cohesive domain structs
 *  while preserving the flat snake_case JSON wire representation.
 */
export type RequestLog = RequestLog_Serialize | RequestLog_Deserialize;

/**
 *  A single request-log record. Categorized into cohesive domain structs
 *  while preserving the flat snake_case JSON wire representation.
 */
export type RequestLog_Deserialize = {
	id: string,
	request_id: string,
	user_id: string | null,
	api_key_id: string | null,
	method: HttpMethod,
	path: string,
	status_code: number,
	latency_ms: number,
	created_at: number,
	provider: string | null,
	model: string | null,
	resolved_model: string | null,
	tokens: LogTokenUsage_Deserialize,
	costs?: LogCost_Deserialize | null,
} & LogClient_Deserialize & LogError_Deserialize;

/**
 *  A single request-log record. Categorized into cohesive domain structs
 *  while preserving the flat snake_case JSON wire representation.
 */
export type RequestLog_Serialize = {
	id: string,
	request_id: string,
	user_id: string | null,
	api_key_id: string | null,
	method: HttpMethod,
	path: string,
	status_code: number,
	latency_ms: number,
	created_at: number,
	provider: string | null,
	model: string | null,
	resolved_model: string | null,
	tokens: LogTokenUsage_Serialize,
	costs?: LogCost_Serialize | null,
} & LogClient_Serialize & LogError_Serialize;

export type SettingsResponse = {
	require_api_key: boolean,
};

/**
 *  Partial update accepted by `PATCH /v1/keys/:id`. Every field is optional;
 *  absent fields are left untouched. `allowed_models` distinguishes absent
 *  (`None`) from an explicit clear (`Some(None)`).
 */
export type UpdateAPIKeyInput = {
	name?: string | null,
	enabled?: boolean | null,
	rate_limit?: number | null,
	quota_limit?: number | null,
	credit_limit?: number | null,
	allowed_models?: string[] | null,
};

/**  One `by_model` entry of [`UsageStatsReport`]. */
export type UsageByModel = {
	model: string,
	total_requests: number,
	total_input_tokens: number,
	total_output_tokens: number,
	total_cached_tokens: number,
	est_cost: number | null,
};

/**
 *  The all-time usage totals served by `GET /v1/logs/stats` and carried by the
 *  `usage.updated` event. The wire keys are snake_case, as documented in
 *  `docs/api-v1-contract.md`, "Logs in the Rust build".
 */
export type UsageStatsReport = {
	object: ObjectKind,
	total_requests: number,
	total_success_requests: number,
	total_tokens: number,
	total_prompt_tokens: number,
	total_completion_tokens: number,
	total_cached_tokens: number,
	total_cache_creation_tokens: number,
	total_reasoning_tokens: number,
	total_estimated_cost: number | null,
	total_input_tokens: number,
	total_output_tokens: number,
	cost_label: string,
	estimated: boolean,
	by_model: UsageByModel[],
};
